"""Add audit trail and final_due_date fields

Revision ID: 247db0fa093e
Revises: 069388395e1c
Create Date: 2025-10-19 21:40:29.118404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247db0fa093e'
down_revision = '069388395e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extension_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('canvas_override_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('notification_sent', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['approved_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extension_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('notification_sent')
        batch_op.drop_column('canvas_override_id')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by_id')
        batch_op.drop_column('final_due_date')

    # ### end Alembic commands ###
