"""add_upload_options_to_policy

Revision ID: caf80094fe69
Revises: a323bb64442c
Create Date: 2025-10-20 11:13:13.123853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf80094fe69'
down_revision = 'a323bb64442c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extension_policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_canvas_upload', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allow_email_upload', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extension_policies', schema=None) as batch_op:
        batch_op.drop_column('allow_email_upload')
        batch_op.drop_column('allow_canvas_upload')

    # ### end Alembic commands ###
