name: CD Pipeline

on:
    workflow_run:
        workflows: ["CI Pipeline"]
        types:
            - completed

jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Pull docker image from docker hub
              #   run: sudo docker pull ${{ vars.DOCKER_USERNAME }}/cicd-workflows-image:latest # docker pull chriscardenas/my-image:latest
              run: sudo docker compose -f docker-compose.prod.yml pull

            - name: Build and run docker container
              run: sudo docker compose -f docker-compose.prod.yml up -d --build

            - name: SHow running containers
              run: sudo docker compose -f docker-compose.prod.yml ps
