name: CD Pipeline

on:
    workflow_run:
        workflows: ["CI_Pipeline"]
        types:
            - completed
        branches:
            - docker

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy on EC2 via SSH
              uses: appleboy/ssh-action@v1.2.0
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      cd /home/ec2-user/extension-requests-app
                      git fetch --all
                      git checkout docker
                      git pull origin docker
                      docker compose -f docker-compose.prod.yml pull
                      docker compose -f docker-compose.prod.yml up -d
                      docker compose -f docker-compose.prod.yml ps
                  #   sudo docker compose pull
                  #   sudo docker compose up -d
                  #   sudo docker compose ps
